# NumPy array

In [2]:
import numpy as  np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
arr.size

4

In [4]:
arr.ndim

1

In [5]:
arr.shape

(4,)

# reshape() function

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(2,-1)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(-1,2)
arr2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [12]:
#Creation of 3D array
arr3 = np.array([1,2,3,4,5,6,7,8]).reshape(2,2,2)
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

#  zeros(), #eye(),  #diag() function

In [13]:
a = np.zeros(4)
a

array([0., 0., 0., 0.])

In [14]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.diag([14,11,20001])

array([[   14,     0,     0],
       [    0,    11,     0],
       [    0,     0, 20001]])

# randint() and rand() function

In [17]:
np.random.randint(1,10,4)


array([6, 3, 6, 4])

In [19]:
np.random.rand(5)

array([0.12838088, 0.98481706, 0.289293  , 0.86733098, 0.09520341])

In [21]:
arr = np.random.randint(1,50,10).reshape(2,5)
arr

array([[47, 48, 43, 37, 40],
       [46, 19, 10, 23, 46]])

# indexing and Slicing of NumPy array

In [24]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [25]:
arr[2:]

array([3, 4, 5])

In [26]:
arr[-1:]

array([5])

In [27]:
arr[-3:]

array([3, 4, 5])

In [28]:
arr[1:4]

array([2, 3, 4])

In [29]:
arr[0:5:3]

array([1, 4])

In [30]:
# reversing of an array
arr[: :-1]

array([5, 4, 3, 2, 1])

In [31]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
#first 1D array
matrix[0]

array([1, 2, 3])

In [33]:
#first element of fisrt 1D array
matrix[0][0]

1

In [34]:
#using only single bracket
matrix[0,1]


2

In [35]:
matrix[:2, :2]

array([[1, 2],
       [4, 5]])

In [36]:
matrix[1:,1:]

array([[5, 6],
       [8, 9]])

In [38]:
np.random.seed(123)
arr = np.random.randint(1,101,25).reshape(5,5)
arr

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [39]:
arr[1:4,1:4]

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])

# view vs copy

In [42]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [43]:
sliced_array = arr[2:4]
sliced_array

array([3, 4])

In [48]:
sliced_array[:]=0
sliced_array


array([0, 0])

In [45]:
arr         #view reflect changes in original array

array([1, 2, 0, 0, 5])

In [50]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [51]:
sliced_array=arr[2:4].copy()
sliced_array

array([3, 4])

In [52]:
sliced_array[:]=0
sliced_array

array([0, 0])

In [54]:
arr #copy does not reflect changes in original array

array([1, 2, 3, 4, 5])

# Conditinal selection

In [3]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr = np.random.randint(1,10,9).reshape(3,3)
arr

array([[8, 9, 5],
       [4, 3, 8],
       [7, 1, 7]])

In [6]:
arr[arr%2==0]

array([8, 4, 8])

In [7]:
arr[arr>8]

array([9])

In [9]:
arr[arr%2 !=0]

array([9, 5, 3, 7, 1, 7])

# NumPy axis

for rows put axis =1 and columns put axis = 0

In [11]:
np.random.seed(123)
arr = np.random.randint(1,10,9).reshape(3,3)
arr

array([[3, 3, 7],
       [2, 4, 7],
       [2, 1, 2]])

In [12]:
# calculate min element rowwise
np.min(arr,axis=1)

array([3, 2, 1])

In [13]:
# calculate max element columnswise
np.max(arr,axis=0)

array([3, 4, 7])

# hstack() and vstack() function

these are used to concatinate two matrices  horizontally and vertically

In [14]:
matrix1 = np.random.randint(1,11,9).reshape(3,3)
matrix1

array([[10,  1,  1],
       [10,  4,  5],
       [ 1,  1,  5]])

In [20]:
np.random.seed(123)
matrix2 = np.random.randint(50,100,9).reshape(3,3)
matrix2

array([[95, 52, 78],
       [84, 88, 67],
       [69, 92, 72]])

In [22]:
np.hstack((matrix1,matrix2))

array([[10,  1,  1, 95, 52, 78],
       [10,  4,  5, 84, 88, 67],
       [ 1,  1,  5, 69, 92, 72]])

In [23]:
np.vstack((matrix2,matrix1))

array([[95, 52, 78],
       [84, 88, 67],
       [69, 92, 72],
       [10,  1,  1],
       [10,  4,  5],
       [ 1,  1,  5]])